apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../kubernetes/apps/o11y/kube-prometheus-stack
  - ../../../secrets/grafana
  - httproute.yaml
patches:
  - path: oidc.yaml

transformers:
  - ../../../transformers
