apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: velero-ui
    repo: https://helm.otwld.com
    version: 0.16.0
    releaseName: velero-ui
    namespace: velero
    valuesFile: values.yaml
    skipTests: true
