# envoy-gateway corre en prod. La definición está en kubernetes/apps/.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../../kubernetes/apps/network/envoy-gateway
