apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: o11y
configMapGenerator:
  - name: gatus-config
    files:
      - config.yaml
helmCharts:
  - name: gatus-sidecar
    repo: oci://ghcr.io/home-operations/charts
    version: 0.5.3
    releaseName: gatus
    namespace: o11y
    valuesFile: values.yaml
    skipTests: true
