.:53 {
    errors
    health {
       lameduck 5s
    }
    ready
    # Las rutas locales llegan a Envoy tambien desde los pods.
    rewrite stop name regex ^(.*)\.{{ regexQuoteMeta .Values.domain }}\.$ envoy-external.network.svc.cluster.local. answer auto
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       fallthrough in-addr.arpa ip6.arpa
       ttl 30
    }
    prometheus :9153
    forward . /etc/resolv.conf {
       max_concurrent 1000
    }
    cache 30 {
       disable success cluster.local
       disable denial cluster.local
    }
    loop
    reload
    loadbalance
}
