apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../secrets/stackgres
  - httproute.yaml
  - objectstorage.yaml
  - oidc-rbac.yaml
components:
  - ../../../../../kubernetes/apps/stackgres/stackgres/patches
generators:
  - ../../../generators
configMapGenerator:
  - name: stackgres-restapi-config
    namespace: stackgres
    files:
      - application.properties
    options:
      disableNameSuffixHash: true

transformers:
  - ../../../transformers
