apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: stackgres-operator
    repo: https://stackgres.io/downloads/stackgres-k8s/stackgres/helm
    version: 1.19.1
    releaseName: stackgres-operator
    namespace: stackgres
    valuesFile: values.yaml
    includeCRDs: true
    skipTests: true
components:
  - patches
