apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../config
patches:
  - target:
      kind: HelmChartInflationGenerator
    patch: |-
      $patch: delete
      apiVersion: builtin
      kind: HelmChartInflationGenerator
      metadata:
        name: unused
